routes/web.php
<?php

use App\Models\Post;
use Illuminate\Support\Facades\Route;
use Spatie\DbDumper\Databases\PostgreSql;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.index');
});

Route::group([
    'namespace' => 'Front',
    'as' => 'front.',
], function () {

    Route::get('/', 'MainController@index')->name('index');
    Route::get('/news','PostController@index')->name('news.index');
    Route::get('/news/all','PostController@all')->name('news.all');
    Route::get('/news/tag/{tag}/{alias?}','PostController@tag')->name('news.tag.index');
    Route::get('/news/category/{category}/{alias?}','PostController@catagory')->name('news.category.index');
    Route::get('/news/{post}/{alias?}','PostController@show')->name('news.show');







//    Route::get('/post/{post}', function (Post $post) {
//        $oldLocale = session()->get('old_locale');
//        $locale = \App::getLocale();
//        $post = Post::where('alias->'.$locale,$post)->get();
//
//        if ($post === null && $oldLocale !== null && $oldLocale !== $locale) {
//            $post = Post::where('alias->'.$oldLocale,$post)->get();
//            if ($post === null) abort(404);
//            return redirect()->route('front.post.show',['post' => $post->alias]);
//        }
//
//        $langs = \App\Models\Language::all();
//
//        foreach ($langs as $lang){
//            $one = Post::where('alias->'.$lang->alias,$post)->get();
//
//            if ($one === null) abort(404);
//
//            return redirect()->route('front.post.show',['post' => $post->alias]);
//
//        }
//
//
//        Post::query()->whereRaw('(alias->\'en\')::jsonb ? \'dsadadad\'')->get()->dd();
//
//
//    })->name('post.show');




//    Route::get('post/create/{current_lang}','PostController@create')->name('post.create');

});

Auth::routes();

Route::group([
    'prefix' => 'dashboard',
    'namespace' => 'Dashboard',
    'as' => 'dashboard.',
], function () {
    Route::get('/', function () {})->name('index');
    Route::resource('tag', 'TagController')->except(['show', 'create', 'edit']);
    Route::resource('post', 'PostController')->except(['show']);
    Route::resource('event', 'EventController')->except(['show']);
    Route::resource('page', 'PageController')->except(['show']);
//    Route::get('post/create/{current_lang}','PostController@create')->name('post.create');

    Route::post('/file-upload', 'FileUploadController@upload')->name('file-upload');
    Route::delete('/file-delete', 'FileUploadController@destroy')->name('file-delete');
    Route::get('/file-get/{file}', 'FileUploadController@show')->name('file-get');


});

app/Models/Event.php
<?php

namespace App\Models;

use App\Helpers\Traits\HasAuthor;
use App\Helpers\Traits\HasCreator;
use App\Helpers\Traits\HasUpdater;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Translatable\HasTranslations;

/**
 * App\Models\Event
 *
 * @property int $id
 * @property string $title
 * @property string $alias
 * @property string|null $image
 * @property int $user_id
 * @property string|null $content
 * @property string $date
 * @property string $time
 * @property string|null $site
 * @property string|null $email
 * @property string|null $address
 * @property string|null $organizer
 * @property string|null $map
 * @property int|null $created_by
 * @property int|null $updated_by
 * @property int|null $deleted_by
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string|null $deleted_at
 * @method static \Illuminate\Database\Eloquent\Builder|Event newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Event newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Event query()
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereAlias($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereCreatedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereDeletedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereMap($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereOrganizer($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereSite($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereTime($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereUpdatedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereUserId($value)
 * @mixin \Eloquent
 * @property-read \App\Models\User $author
 * @property-read \App\Models\User|null $creator
 * @property-read array $translations
 * @property-read \App\Models\User|null $updater
 * @method static \Illuminate\Database\Query\Builder|Event onlyTrashed()
 * @method static \Illuminate\Database\Query\Builder|Event withTrashed()
 * @method static \Illuminate\Database\Query\Builder|Event withoutTrashed()
 * @property-read \App\Models\User $user
 * @property int $event_theme_id
 * @property int $event_type_id
 * @property string $place
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereEventThemeId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event whereEventTypeId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Event wherePlace($value)
 */
class Event extends Model
{
    use HasFactory,HasCreator,HasUpdater,SoftDeletes,HasTranslations,HasAuthor;

    protected $translatable = ['title','content','address','organizer','place'];

    protected $fillable = ['title','alias','content','image','user_id','date','time','site','phone','email','address','organizer','map','place','event_theme_id','event_type_id','created_by','updated_by','deleted_by','created_at'];

    public function visits(): Relation
    {
        return visits($this)->relation();
    }

    public function getViewsAttribute(): int
    {
        return $this->visits()->count();
    }


    public static function fields(): array
    {
        return [
            'title' => [
                'ru' => 'string',
                'en' => 'string',
                'uz' => 'string',
            ],
            'alias' => [
                'ru' => 'string',
                'en' => 'string',
                'uz' => 'string',
            ],
            'content' => [
                'ru' => 'string',
                'en' => 'string',
                'uz' => 'string',
            ],
            'image' => 'string',
            'views' => 'string',
            'shares' => 'string',
            'type' => 'string',
            'place' => 'string',
            'author' => [],
            'date' => 'string',
            'time' => 'time',
            'site' => 'string',
            'email' => 'string',
            'address' => [
                'ru' => 'string',
                'en' => 'string',
                'uz' => 'string',
            ],
            'organizer' => [
                'ru' => 'string',
                'en' => 'string',
                'uz' => 'string',
            ],
            'map' => 'string|url',
            'created_at' => 'datetime'
        ];
    }

}

app/Models/EventType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Spatie\Sluggable\HasTranslatableSlug;
use Spatie\Sluggable\SlugOptions;
use Spatie\Translatable\HasTranslations;

/**
 * App\Models\EventType
 *
 * @property int $id
 * @property array $title
 * @property array $alias
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Event[] $events
 * @property-read int|null $events_count
 * @property-read array $translations
 * @method static \Illuminate\Database\Eloquent\Builder|EventType newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|EventType newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|EventType query()
 * @method static \Illuminate\Database\Eloquent\Builder|EventType whereAlias($value)
 * @method static \Illuminate\Database\Eloquent\Builder|EventType whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|EventType whereTitle($value)
 * @mixin \Eloquent
 */
class EventType extends Model
{
    use HasFactory,HasTranslations;

    protected $fillable = ['title','alias'];

    protected $translatable = ['title'];

    public $timestamps = false;

    public function events(): HasMany
    {
        return $this->hasMany(Event::class,'event_type_id');
    }
}

app/Http/Controllers/Dashboard/EventController.php
<?php


namespace App\Http\Controllers\Dashboard;


use App\Actions\Dashboard\Event\CreateEventAction;
use App\Actions\Dashboard\Event\UpdateEventAction;
use App\DTO\EventDTO;
use App\Http\Requests\Dashboard\EventRequest;
use App\Models\Event;
use App\Models\EventTheme;
use App\Models\EventType;
use App\Models\Language;
use App\Models\User;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class EventController extends BaseDashboardController
{

    public function index(){
        $langs = Language::all();
        $events = Event::all();
        return view('dashboard.pages.event.index',compact('langs','events'));
    }

    public function create(){
        $langs = Language::all();
        $theme = EventTheme::all();
        $type = EventType::all();
        $authors = User::query()->latest()->get();

        return view('dashboard.pages.event.create',compact('langs','theme','type','authors'));
    }

    public function store(EventRequest $request,CreateEventAction $createEventAction): RedirectResponse
    {
        try {
            $event = $createEventAction->execute(EventDTO::fromRequest($request));
            alert()->success($event->getTranslation('title',$request->input('lang'),__('actions.added')));
            return redirect()->route('dashboard.event.index');
        }catch (Exception $exception){
            dd($exception);
            alert()->error(__('dashboard.event.title'),__('actions.not_saved'));
            return redirect()->route('dashboard.event.create')->withInput();
        }
    }

    public function edit(Request $request,Event $event){
        $langs = Language::all();
        $theme = EventTheme::all();
        $type = EventType::all();
        $authors = User::query()->latest()->get();
        $current_lang = $request->get('lang') ?? app()->getLocale();
        return view('dashboard.pages.event.edit',compact('langs','theme','type','authors','event','current_lang'));
    }

    public function update(EventRequest $request,Event $event,UpdateEventAction $updateEventAction): RedirectResponse
    {

        try {
            $event = $updateEventAction->execute(EventDTO::fromRequest($request,EventDTO::UPDATING),$event);
            alert()->success($event->getTranslation('title',$request->input('lang')),__('actions.updated'));
            return redirect()->route('dashboard.event.edit',['event' => $event->id,'lang' => $request->input('lang')]);
        }catch (Exception $exception){
            alert()->error(__('dashboard.event.index'),__('actions.not_updated'));
            return redirect()->route('dashboard.event.edit',['event' => $event->id])->withInput();
        }
    }

    public function destroy(Event $event): JsonResponse
    {
        if (request()->wantsJson()){
            try {
                $event->delete();
                return response()->json([
                    'status' => 'success',
                    'message' => [
                        'title' => __('message.deleted'),
                        'text' => __('message.model_deleted')
                    ]
                ]);
            }catch (Exception $exception){
                return response()->json([
                    'status' => 'success',
                    'message' => [
                        'title' => __('message.code_500')
                    ]
                ],500);
            }
        }
        abort(404);
    }

}

resources/views/dashboard/pages/event/edit.blade.php
<?php

resources/views/dashboard/pages/event/index.blade.php
@extends('dashboard.layouts.app')


@section('title', __('dashboard.page.index'))

@section('vendor-style')
    {{-- vendor files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
    {{--  <link rel="stylesheet" href="{{ asset(mix('vendors/css/file-uploaders/dropzone.min.css')) }}">--}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/extensions/dataTables.checkboxes.css')) }}">
@endsection
@section('page-style')
    {{-- Page css files --}}
    <link rel="stylesheet" href="{{ asset(mix('css/pages/data-list-view.css')) }}">
@endsection

@section('content')
    {{-- Data list view starts --}}
    <section id="data-list-view" class="data-list-view-header">
        <div class="action-btns d-none">
            <div class="btn-dropdown mr-1 mb-1">
                <div class="btn-group dropdown actions-dropodown">
                    <button type="button" class="btn btn-white px-1 py-1 dropdown-toggle waves-effect waves-light"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ __('actions.title') }}
                    </button>
                    <div class="dropdown-menu">
                        {{--            <a class="dropdown-item" href="#"><i class="feather icon-plus-circle"></i>{{ __('dashboard.action.add_package') }}</a>--}}
                        @forelse($pageTypes as $type)
                            @if($type->name !== \App\Models\PageType::RECTOR and $type->name !== \App\Models\PageType::SIMPLE)
                                <a class="dropdown-item" href="{{ route('dashboard.page.create',['type' => $type->name]) }}"><i class="feather {{ $type->icon }}"></i>{{ __('actions.create_'.$type->name.'_page') }}</a>
                            @else
                                @if($hasRectorPage and $type->name === \App\Models\PageType::RECTOR)
                                    <a class="dropdown-item" href="{{ route('dashboard.page.create',['type' => $type->name]) }}"><i class="feather {{ $type->icon }}"></i>{{ __('actions.create_'.$type->name.'_page') }}</a>
                                @endif
                            @endif
                        @empty
                        @endforelse
                        <a class="dropdown-item" href="{{ route('dashboard.page.create') }}"><i class="feather icon-plus"></i>{{ __('dashboard.page.add') }}</a>
                    </div>
                </div>
                <div class="btn-group dropdown actions-dropodown">
                    <a href="{{ route('dashboard.page.create') }}" class="btn btn-primary px-1 py-1 waves-effect waves-light js__add">
                        <i class="feather icon-plus"></i>{{ __('dashboard.page.add') }}
                    </a>
                </div>
            </div>
        </div>

        {{-- DataTable starts --}}
        <div class="table-responsive">
            <table class="table data-list-view">
                <thead>
                <tr>
                    <th></th>
                    <th>{{ __('dashboard.page.title') }}</th>
                    <th>{{ __('Language') }}</th>
                    <th>{{ __('dashboard.page.type') }}</th>
                    <th>{{ __('dashboard.tag.created_at') }}</th>
                    <th>{{ __('actions.title') }}</th>
                </tr>
                </thead>
                <tbody>
                @forelse($pages as $page)
                    <tr>
                        <td></td>
                        <td>{{ $page->getTranslation('title',app()->getLocale()) }}</td>
                        <td>
                            @foreach($langs as $lang)
                                <span>
                                    <i class="{{ $lang->icon }} ml-1"></i>
                                    @if($page->hasTranslation('title',$lang->alias) and $page->hasTranslation('content',$lang->alias))
                                        <i class="feather icon-check-circle text-success"></i>
                                    @else
                                        <i class="feather icon-x-circle text-danger"></i>
                                    @endif
                                </span>
                            @endforeach
                        </td>
                        <td>
                            <i class="feather {{ $page->type->icon ?? 'icon-layout' }} text-info"></i>
                        </td>
                        <td>
                            {{ $page->created_at->format("d.m.Y H:i") }}
                        </td>
                        <td>
                            <a href="{{ route('dashboard.page.edit',['page' => $page->id,'lang' => app()->getLocale()]) }}" class="text-primary">
                                <i class="feather icon-edit"></i>
                            </a>
                            @if($page->type->name !== \App\Models\PageType::RECTOR)
                                <span class="text-danger" onclick="js_delete('{{route('dashboard.page.destroy',['page' => $page->id])}}')">
                                    <i class="feather icon-trash"></i>
                                </span>
                            @endif
                        </td>
                    </tr>
                @empty

                @endforelse
                </tbody>
            </table>
        </div>


        {{-- DataTable ends --}}
    </section>
    {{-- Data list view end --}}
@endsection
@section('vendor-script')
    {{-- vendor js files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.select.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.checkboxes.min.js')) }}"></script>
    <script src="{{ asset('vendor/axios/axios.min.js') }}"></script>
@endsection
@section('page-script')

    <script>

        // init list view datatable
        var dataListView = $(".data-list-view").DataTable({
            responsive: false,
            columnDefs: [
                {
                    orderable: true,
                    targets: 0,
                    checkboxes: { selectRow: true }
                }
            ],
            dom:
                '<"top"<"actions action-btns"B><"action-filters"lf>><"clear">rt<"bottom"<"actions">p>',
            oLanguage: {
                sLengthMenu: "_MENU_",
                sSearch: ""
            },
            aLengthMenu: [[5, 10, 15, 20], [5, 10, 15, 20]],
            select: {
                style: "multi"
            },
            order: [[1, "asc"]],
            bInfo: false,
            pageLength: 10,
            buttons: [],
            initComplete: function(settings, json) {
                $(".dt-buttons .btn").removeClass("btn-secondary")
            }
        });

        dataListView.on('draw.dt', function(){
            setTimeout(function(){
                if (navigator.userAgent.indexOf("Mac OS X") != -1) {
                    $(".dt-checkboxes-cell input, .dt-checkboxes").addClass("mac-checkbox")
                }
            }, 50);
        });
        // To append actions dropdown before add new button
        var actionDropdown = $(".actions-dropodown")
        actionDropdown.insertBefore($(".top .actions .dt-buttons"))
        // Scrollbar
        if ($(".data-items").length > 0) {
            new PerfectScrollbar(".data-items", { wheelPropagation: false })
        }
        // mac chrome checkbox fix
        if (navigator.userAgent.indexOf("Mac OS X") != -1) {
            $(".dt-checkboxes-cell input, .dt-checkboxes").addClass("mac-checkbox")
        }

        function js_delete(route){
            Swal.fire({
                title: '{{ __('message.are_you_sure') }}',
                text: '{{ __('message.dont_revert') }}',
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: '{{ __('message.yes_delete') }}',
                cancelButtonText: '{{ __('message.cancel') }}',
                customClass: {
                    confirmButton: 'btn btn-primary',
                    cancelButton: 'btn btn-outline-danger ml-1'
                },
                buttonsStyling: false
            }).then(function (result) {
                if (result.value) {
                    axios.delete(route).then(response => {
                        let data = response.data
                        if (data.status === 'success'){
                            Swal.fire({
                                title: data.message.title,
                                text: data.message.text,
                                type: 'success',
                                showCancelButton: false,
                                confirmButtonText: 'Ok',
                                customClass: {
                                    confirmButton: 'btn btn-primary',
                                },
                                buttonsStyling: false
                            }).then(function (result){
                                if (result.value){
                                    window.location.reload()
                                }else{

                                }
                            });
                        }
                    }).catch(response => {
                        Swal.fire({
                            type: 'error',
                            title: '{{ __('message.deleted') }}',
                            customClass: {
                                confirmButton: 'btn btn-success'
                            }
                        });
                    })

                }
            });
        }

    </script>
@endsection